### ISSUE TITLE
SqlTools.openConnection(String) does not use parameter

### ISSUE THREAD

**Issue by FrodeRanders** [l3nz/ObjectiveSync#1]
The 'connString' parameter is never used. Instead, a **hard-coded** connection string is used.

```
public static Connection openConnection(String connString) throws SQLException {
    Connection conn = DriverManager.getConnection("jdbc:h2:mem:test");
    return conn;
}
```

**Comment by l3nz** [comment]
Thanks for pointing that out, I'll have a new build out.
I actually use OS mostly in an environment where I already have a JDBC connection so dont really use that function. But of course that's a major showstopper. :)
